# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from theta_py import Theta
from theta_py._generated import outcomes, verbs


def _binary_available() -> bool:
    from theta_py.runner import ThetaBinaryNotFoundError, _resolve_binary

    try:
        _resolve_binary(auto_install=False)
        return True
    except (ThetaBinaryNotFoundError, FileNotFoundError):
        return shutil.which("theta") is not None


pytestmark = pytest.mark.skipif(
    not _binary_available(),
    reason="theta binary not resolvable",
)


@pytest.fixture
def workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("THETA_DATA_DIR", str(data_dir))
    monkeypatch.delenv("THETA_CONFIG_DIR", raising=False)
    verbs._theta = None
    yield tmp_path
    verbs._theta = None


def _setup_init(t: Theta) -> None:
    t.init(name="smoke-setup")


def _setup_init_rule(t: Theta) -> None:
    t.init(name="smoke-setup")
    t.add.rule("smoke-rule")


def _setup_init_sync(t: Theta) -> None:
    t.init(name="smoke-setup")
    t.add.system(content="smoke system prompt")
    t.sync()


SETUP: dict[str, callable] = {
    "none": lambda t: None,
    "init": _setup_init,
    "init+rule": _setup_init_rule,
    "init+sync": _setup_init_sync,
}


def test_smoke_init_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['none'](t)
    out = t.init(name='smoke')
    assert isinstance(out, outcomes.InitOutcome)


def test_smoke_init_flat(workspace: Path) -> None:
    SETUP['none'](Theta())
    out = verbs.init(name='smoke')
    assert isinstance(out, outcomes.InitOutcome)


def test_smoke_check_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.check()
    assert isinstance(out, outcomes.CheckOutcome)


def test_smoke_check_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.check()
    assert isinstance(out, outcomes.CheckOutcome)


def test_smoke_describe_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.describe()
    assert isinstance(out, outcomes.DescribeOutcome)


def test_smoke_describe_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.describe()
    assert isinstance(out, outcomes.DescribeOutcome)


def test_smoke_add_rule_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.add.rule(name='smoke-rule')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_rule_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.add_rule(name='smoke-rule')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_system_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.add.system()
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_system_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.add_system()
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_tool_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.add.tool(name='smoke-tool', command='echo hi')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_tool_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.add_tool(name='smoke-tool', command='echo hi')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_skill_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.add.skill(name_or_ref='smoke-skill')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_skill_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.add_skill(name_or_ref='smoke-skill')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_subagent_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.add.subagent(name='smoke-subagent', description='smoke', description_only=True)
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_add_subagent_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.add_subagent(name='smoke-subagent', description='smoke', description_only=True)
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_rm_rule_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init+rule'](t)
    out = t.rm.rule(name='smoke-rule', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_rm_rule_flat(workspace: Path) -> None:
    SETUP['init+rule'](Theta())
    out = verbs.rm_rule(name='smoke-rule', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_system_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.rm.system(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_system_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.rm_system(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_tool_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.rm.tool(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_tool_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.rm_tool(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_skill_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.rm.skill(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_skill_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.rm_skill(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_subagent_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.rm.subagent(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='rm of missing entity returns error envelope; not a smoke target')
def test_smoke_rm_subagent_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.rm_subagent(name='missing', no_sync=True)
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires populated system store')
def test_smoke_rm_store_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.rm.store(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires populated system store')
def test_smoke_rm_store_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.rm_store(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_list_rules_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.list.rules()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_rules_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.list_rules()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_tools_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.list.tools()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_tools_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.list_tools()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_skills_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.list.skills()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_skills_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.list_skills()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_subagents_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.list.subagents()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_subagents_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.list_subagents()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_store_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.list.store()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_list_store_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.list_store()
    assert isinstance(out, outcomes.ListOutcome)


def test_smoke_lock_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.lock()
    assert isinstance(out, outcomes.LockOutcome)


def test_smoke_lock_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.lock()
    assert isinstance(out, outcomes.LockOutcome)


def test_smoke_sync_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.sync()
    assert isinstance(out, outcomes.SyncOutcome)


def test_smoke_sync_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.sync()
    assert isinstance(out, outcomes.SyncOutcome)


def test_smoke_cast_to_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.cast.to(target='claude-code')
    assert isinstance(out, outcomes.CastToOutcome)


def test_smoke_cast_to_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.cast_to(target='claude-code')
    assert isinstance(out, outcomes.CastToOutcome)


@pytest.mark.skip(reason='requires a populated source directory; covered by Rust cast_round_trip tests')
def test_smoke_cast_from_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['none'](t)
    out = t.cast.from_(source='claude-code')
    assert isinstance(out, outcomes.CastFromOutcome)


@pytest.mark.skip(reason='requires a populated source directory; covered by Rust cast_round_trip tests')
def test_smoke_cast_from_flat(workspace: Path) -> None:
    SETUP['none'](Theta())
    out = verbs.cast_from(source='claude-code')
    assert isinstance(out, outcomes.CastFromOutcome)


@pytest.mark.skip(reason='requires a populated system store')
def test_smoke_register_skill_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.register.skill(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires a populated system store')
def test_smoke_register_skill_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.register_skill(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires a populated system store')
def test_smoke_register_rule_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.register.rule(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires a populated system store')
def test_smoke_register_rule_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.register_rule(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires a populated system store')
def test_smoke_register_agent_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.register.agent(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


@pytest.mark.skip(reason='requires a populated system store')
def test_smoke_register_agent_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.register_agent(name='missing')
    assert isinstance(out, outcomes.MutationOutput)


def test_smoke_tree_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init'](t)
    out = t.tree()
    assert isinstance(out, outcomes.TreeOutcome)


def test_smoke_tree_flat(workspace: Path) -> None:
    SETUP['init'](Theta())
    out = verbs.tree()
    assert isinstance(out, outcomes.TreeOutcome)


@pytest.mark.skip(reason='schema verb dumps full TOML schema, not envelope-shaped')
def test_smoke_schema_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['none'](t)
    out = t.schema()
    assert isinstance(out, outcomes.SchemaOutcome)


@pytest.mark.skip(reason='schema verb dumps full TOML schema, not envelope-shaped')
def test_smoke_schema_flat(workspace: Path) -> None:
    SETUP['none'](Theta())
    out = verbs.schema()
    assert isinstance(out, outcomes.SchemaOutcome)


def test_smoke_get_namespaced(workspace: Path) -> None:
    t = Theta()
    SETUP['init+sync'](t)
    out = t.get()
    assert isinstance(out, outcomes.GetOutcome)


def test_smoke_get_flat(workspace: Path) -> None:
    SETUP['init+sync'](Theta())
    out = verbs.get()
    assert isinstance(out, outcomes.GetOutcome)


KNOWN_LEAVES: tuple[tuple[str, ...], ...] = (
    ('add', 'rule'),
    ('add', 'skill'),
    ('add', 'subagent'),
    ('add', 'system'),
    ('add', 'tool'),
    ('cast', 'from'),
    ('cast', 'to'),
    ('check',),
    ('describe',),
    ('get',),
    ('init',),
    ('list', 'rules'),
    ('list', 'skills'),
    ('list', 'store'),
    ('list', 'subagents'),
    ('list', 'tools'),
    ('lock',),
    ('register', 'agent'),
    ('register', 'rule'),
    ('register', 'skill'),
    ('rm', 'rule'),
    ('rm', 'skill'),
    ('rm', 'store'),
    ('rm', 'subagent'),
    ('rm', 'system'),
    ('rm', 'tool'),
    ('schema',),
    ('sync',),
    ('tree',),
)

RECIPED_LEAVES: frozenset[tuple[str, ...]] = frozenset({
    ('add', 'rule'),
    ('add', 'skill'),
    ('add', 'subagent'),
    ('add', 'system'),
    ('add', 'tool'),
    ('cast', 'from'),
    ('cast', 'to'),
    ('check',),
    ('describe',),
    ('get',),
    ('init',),
    ('list', 'rules'),
    ('list', 'skills'),
    ('list', 'store'),
    ('list', 'subagents'),
    ('list', 'tools'),
    ('lock',),
    ('register', 'agent'),
    ('register', 'rule'),
    ('register', 'skill'),
    ('rm', 'rule'),
    ('rm', 'skill'),
    ('rm', 'store'),
    ('rm', 'subagent'),
    ('rm', 'system'),
    ('rm', 'tool'),
    ('schema',),
    ('sync',),
    ('tree',),
})


def test_every_verb_has_a_smoke_recipe() -> None:
    missing = [p for p in KNOWN_LEAVES if p not in RECIPED_LEAVES]
    assert not missing, (
        f'new verbs without a SMOKE_RECIPES entry: {missing}. '
        f'Add them in src/theta_py/_codegen.py.'
    )
