# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.
"""Python bindings for the theta CLI.

Quick start::

    from theta_py import ThetaProject, theta

    with ThetaProject.temp(name="my-agent") as proj:
        proj.add.system(content="You are an expert.")
        proj.sync()
        print(proj.system_prompt)
"""

from typing import Any

from theta_py._version import THETA_VERSION
from theta_py.errors import (
    ThetaBinaryNotFoundError,
    ThetaCommandError,
    ThetaError,
    ThetaInvocationError,
)

__version__ = THETA_VERSION


def __getattr__(name: str) -> Any:
    if name == "ThetaProject":
        from theta_py.project import ThetaProject as _tp

        return _tp
    if name == "ThetaManifest":
        from theta_py._generated.manifest import ThetaManifest as _m

        return _m
    _outcomes = {"AgentInfo", "GetOutcome", "MaterializedRule", "MaterializedSkill", "MaterializedTool"}
    if name in _outcomes:
        from theta_py._generated import outcomes as _o

        return getattr(_o, name)
    from theta_py._generated import verbs as _v

    if name == "theta":
        return _v._get_theta()
    if hasattr(_v, name):
        return getattr(_v, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "THETA_VERSION",
    "AgentInfo",
    "GetOutcome",
    "MaterializedRule",
    "MaterializedSkill",
    "MaterializedTool",
    "Theta",
    "ThetaBinaryNotFoundError",
    "ThetaCommandError",
    "ThetaError",
    "ThetaInvocationError",
    "ThetaManifest",
    "ThetaProject",
]
