from __future__ import annotations

import argparse
import json
import keyword
import shutil
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path
from types import MappingProxyType
from typing import Any

PACKAGE_DIR = Path(__file__).resolve().parent
GENERATED = PACKAGE_DIR / "_generated"
SCHEMAS = PACKAGE_DIR.parent.parent / "schemas"
PROJECT_ROOT = PACKAGE_DIR.parent.parent
GENERATED_TESTS = PROJECT_ROOT / "tests" / "_generated"

AUTOGEN_HEADER = (
    "# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!\n"
    "# Source of truth: `theta schema --list-verbs`.\n"
    "# Regenerate with `python -m theta_py._codegen`.\n"
)


def resolve_binary(override: str | None) -> Path:
    if override is not None:
        path = Path(override)
        if not path.exists():
            raise FileNotFoundError(f"--binary path does not exist: {override}")
        return path
    from theta_py.runner import _resolve_binary

    return _resolve_binary(auto_install=False)


def fetch_verb_tree(binary: Path) -> dict[str, Any]:
    result = subprocess.run(
        [str(binary), "schema", "--list-verbs"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def iter_leaves(node: dict[str, Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    if not node.get("subcommands") and node.get("path"):
        out.append(node)
    for sub in node.get("subcommands", []):
        out.extend(iter_leaves(sub))
    return out


def function_name(path: list[str]) -> str:
    return "_".join(seg.replace("-", "_") for seg in path)


def outcome_class_name(path: list[str]) -> str:
    return "".join(seg.capitalize() for seg in path) + "Outcome"


def kwarg_name(arg_name: str) -> str:
    return f"{arg_name}_" if keyword.iskeyword(arg_name) else arg_name


def is_bool_flag(arg: dict[str, Any]) -> bool:
    return not arg.get("takes_value", False)


def _normalize_schema(node: Any) -> Any:
    """Drop `format: uint*` from integer types; datamodel-codegen rejects it."""
    if isinstance(node, dict):
        if node.get("type") == "integer" and node.get("format", "").startswith("uint"):
            node = {k: v for k, v in node.items() if k != "format"}
        return {k: _normalize_schema(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_normalize_schema(item) for item in node]
    return node


def write_outcomes_module(leaves: list[dict[str, Any]]) -> None:
    combined: dict[str, Any] = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "ThetaOutcomes",
        "type": "object",
        "definitions": {},
    }
    for leaf in leaves:
        schema = leaf.get("output_schema")
        if schema is None:
            continue
        for name, defn in schema.get("definitions", {}).items():
            combined["definitions"][name] = defn
        title = schema.get("title") or outcome_class_name(leaf["path"])
        body = {k: v for k, v in schema.items() if k not in {"$schema", "definitions", "title"}}
        body["title"] = title
        combined["definitions"][title] = body

    combined = _normalize_schema(combined)

    SCHEMAS.mkdir(parents=True, exist_ok=True)
    schema_path = SCHEMAS / "outcomes.json"
    schema_path.write_text(json.dumps(combined, indent=2))

    target = GENERATED / "outcomes.py"
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(target),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.13",
            "--use-standard-collections",
            "--use-union-operator",
            "--collapse-root-models",
            "--use-schema-description",
            "--disable-timestamp",
            "--formatters",
            "black",
            "--formatters",
            "isort",
        ],
        check=True,
    )
    existing = target.read_text()
    target.write_text(AUTOGEN_HEADER + existing)


def _split_args(leaf: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    positional: list[dict[str, Any]] = []
    keyword_args: list[dict[str, Any]] = []
    for arg in leaf.get("args", []):
        (positional if arg.get("long") is None else keyword_args).append(arg)
    return positional, keyword_args


def _render_signature(
    positional: list[dict[str, Any]],
    keyword_args: list[dict[str, Any]],
    *,
    indent: str,
) -> str:
    parts: list[str] = []
    c = parts.append
    for arg in positional:
        py_name = kwarg_name(arg["name"])
        c(f"{py_name}: str" if arg.get("required") else f"{py_name}: str | None = None")
    if keyword_args:
        c("*")
    for arg in keyword_args:
        py_name = kwarg_name(arg["name"])
        if is_bool_flag(arg):
            c(f"{py_name}: bool = False")
        elif arg.get("required"):
            c(f"{py_name}: str")
        else:
            c(f"{py_name}: str | None = None")
    c("cwd: str | os.PathLike[str] | None = None")
    c("env: Mapping[str, str] | None = None")
    return f",\n{indent}".join(parts)


def _render_argv_construction(
    path: list[str],
    positional: list[dict[str, Any]],
    keyword_args: list[dict[str, Any]],
    indent: str,
) -> str:
    lines = [f"{indent}argv: list[str] = {list(path)!r}"]
    c = lines.append
    for arg in positional:
        py_name = kwarg_name(arg["name"])
        if arg.get("required"):
            c(f"{indent}argv.append({py_name})")
        else:
            c(f"{indent}if {py_name} is not None:")
            c(f"{indent}    argv.append({py_name})")
    for arg in keyword_args:
        py_name = kwarg_name(arg["name"])
        long_name = arg["long"]
        if is_bool_flag(arg):
            c(f"{indent}if {py_name}:")
            c(f"{indent}    argv.append('--{long_name}')")
        elif arg.get("required"):
            c(f"{indent}argv.extend(['--{long_name}', {py_name}])")
        else:
            c(f"{indent}if {py_name} is not None:")
            c(f"{indent}    argv.extend(['--{long_name}', {py_name}])")
    return "\n".join(lines)


def _render_call_args(positional: list[dict[str, Any]], keyword_args: list[dict[str, Any]]) -> str:
    parts: list[str] = []
    c = parts.append
    for arg in positional:
        c(kwarg_name(arg["name"]))
    for arg in keyword_args:
        py_name = kwarg_name(arg["name"])
        c(f"{py_name}={py_name}")
    c("cwd=cwd")
    c("env=env")
    return ", ".join(parts)


def method_name(path: list[str]) -> str:
    return kwarg_name(path[-1].replace("-", "_"))


def render_namespace_class(namespace: str, leaves: list[dict[str, Any]]) -> str:
    class_name = namespace.capitalize()
    methods: list[str] = []
    for leaf in leaves:
        path = leaf["path"]
        positional, keyword_args = _split_args(leaf)
        sig = _render_signature(positional, keyword_args, indent="        ")
        argv_body = _render_argv_construction(path, positional, keyword_args, indent="        ")
        outcome_title = (leaf.get("output_schema") or {}).get("title") or outcome_class_name(path)
        docstring = leaf.get("about") or f"theta {' '.join(path)}"
        methods.append(
            f"    def {method_name(path)}(\n"
            f"        self,\n"
            f"        {sig},\n"
            f"    ) -> outcomes.{outcome_title}:\n"
            f'        """{docstring}"""\n'
            f"{argv_body}\n"
            f"        envelope = self._theta._run(argv, cwd=cwd, env=env)\n"
            f"        return outcomes.{outcome_title}.model_validate(envelope['data'])",
        )
    body = "\n\n".join(methods)
    return (
        f"class {class_name}:\n"
        f'    """`theta {namespace}` namespace; methods correspond to subcommands."""\n\n'
        f"    def __init__(self, theta: Theta) -> None:\n"
        f"        self._theta = theta\n\n"
        f"{body}\n"
    )


def render_root_verb_method(leaf: dict[str, Any]) -> str:
    path = leaf["path"]
    positional, keyword_args = _split_args(leaf)
    sig = _render_signature(positional, keyword_args, indent="        ")
    argv_body = _render_argv_construction(path, positional, keyword_args, indent="        ")
    outcome_title = (leaf.get("output_schema") or {}).get("title") or outcome_class_name(path)
    docstring = leaf.get("about") or f"theta {' '.join(path)}"
    return (
        f"    def {method_name(path)}(\n"
        f"        self,\n"
        f"        {sig},\n"
        f"    ) -> outcomes.{outcome_title}:\n"
        f'        """{docstring}"""\n'
        f"{argv_body}\n"
        f"        envelope = self._run(argv, cwd=cwd, env=env)\n"
        f"        return outcomes.{outcome_title}.model_validate(envelope['data'])"
    )


def render_flat_function(leaf: dict[str, Any]) -> str:
    path = leaf["path"]
    fn_name = function_name(path)
    positional, keyword_args = _split_args(leaf)
    sig = _render_signature(positional, keyword_args, indent="    ")
    call_args = _render_call_args(positional, keyword_args)
    outcome_title = (leaf.get("output_schema") or {}).get("title") or outcome_class_name(path)
    docstring = leaf.get("about") or f"theta {' '.join(path)}"
    if len(path) == 1:
        call_expr = f"_get_theta().{method_name(path)}({call_args})"
    else:
        call_expr = f"_get_theta().{path[0]}.{method_name(path)}({call_args})"
    return (
        f"def {fn_name}(\n"
        f"    {sig},\n"
        f") -> outcomes.{outcome_title}:\n"
        f'    """{docstring}"""\n'
        f"    return {call_expr}\n"
    )


def write_verbs_module(leaves: list[dict[str, Any]]) -> None:
    namespaces: dict[str, list[dict[str, Any]]] = {}
    root_leaves: list[dict[str, Any]] = []
    for leaf in leaves:
        if leaf.get("output_schema") is None:
            continue
        path = leaf["path"]
        if len(path) == 1:
            root_leaves.append(leaf)
        else:
            namespaces.setdefault(path[0], []).append(leaf)

    lines: list[str] = [
        AUTOGEN_HEADER,
        "from __future__ import annotations",
        "",
        "import os",
        "from collections.abc import Mapping",
        "from pathlib import Path",
        "from typing import Any",
        "",
        "from theta_py import runner",
        "from theta_py._generated import outcomes",
        "",
        "",
    ]

    c = lines.append

    for namespace in sorted(namespaces):
        c(render_namespace_class(namespace, namespaces[namespace]))
        c("")

    c("class Theta:")
    c("    def __init__(")
    c("        self,")
    c("        *,")
    c("        binary: str | os.PathLike[str] | None = None,")
    c("        cwd: str | os.PathLike[str] | None = None,")
    c("        env: Mapping[str, str] | None = None,")
    c("    ) -> None:")
    c("        self._binary: Path = Path(binary) if binary is not None else runner._resolve_binary()")
    c("        self._cwd = cwd")
    c("        self._env = env")
    for namespace in sorted(namespaces):
        c(f"        self.{namespace} = {namespace.capitalize()}(self)")
    c("")
    c("    def _run(")
    c("        self,")
    c("        argv: list[str],")
    c("        *,")
    c("        cwd: str | os.PathLike[str] | None = None,")
    c("        env: Mapping[str, str] | None = None,")
    c("    ) -> dict[str, Any]:")
    c("        # Resolution order: explicit per-call cwd --> instance cwd --> live os.getcwd()")
    c("        # at call time. The last branch matches subprocess semantics: a long-lived")
    c("        # Theta() that was constructed before chdir() still follows the process.")
    c("        if cwd is not None:")
    c("            effective_cwd = cwd")
    c("        elif self._cwd is not None:")
    c("            effective_cwd = self._cwd")
    c("        else:")
    c("            effective_cwd = os.getcwd()")
    c("        effective_env = env if env is not None else self._env")
    c("        return runner.run_with_binary(self._binary, argv, cwd=effective_cwd, env=effective_env)")
    c("")
    for leaf in root_leaves:
        c(render_root_verb_method(leaf))
        c("")

    # Lazy singleton backing both the public `theta` re-export and the
    # flat module-level functions. Module-level __getattr__ would NOT work
    # here because LOAD_GLOBAL inside function bodies bypasses it.
    c("")
    c("_theta: Theta | None = None")
    c("")
    c("")
    c("def _get_theta() -> Theta:")
    c("    global _theta")
    c("    if _theta is None:")
    c("        _theta = Theta()")
    c("    return _theta")
    c("")
    c("")

    for leaf in root_leaves:
        c(render_flat_function(leaf))
        c("")
    for namespace in sorted(namespaces):
        for leaf in namespaces[namespace]:
            c(render_flat_function(leaf))
            c("")

    (GENERATED / "verbs.py").write_text("\n".join(lines))


def fetch_manifest_schema(binary: Path) -> dict[str, Any]:
    result = subprocess.run(
        [str(binary), "schema", "--output-format", "json"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def write_manifest_module(binary: Path) -> None:
    """Generate ``_generated/manifest.py`` from ``theta schema --output-format json``.

    The module contains a Pydantic ``ThetaManifest`` model and all referenced
    sub-types (``Agent``, ``Instructions``, ``Rule``, ``Skill``, etc.).
    These are the Python counterparts of the Rust ``theta-schema`` types.
    """
    schema = fetch_manifest_schema(binary)
    schema = _normalize_schema(schema)

    SCHEMAS.mkdir(parents=True, exist_ok=True)
    schema_path = SCHEMAS / "manifest.json"
    schema_path.write_text(json.dumps(schema, indent=2))

    target = GENERATED / "manifest.py"
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(target),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.12",
            "--use-standard-collections",
            "--use-union-operator",
            "--collapse-root-models",
            "--use-schema-description",
            "--disable-timestamp",
            "--formatters",
            "black",
            "--formatters",
            "isort",
        ],
        check=True,
    )
    existing = target.read_text()
    target.write_text(AUTOGEN_HEADER + existing)


def write_constants_module(binary: Path) -> None:
    """Generate ``_generated/constants.py`` from ``theta schema --constants``.

    Produces ``Final[str]`` constants for all theta-static path names so
    ``project.py`` never hardcodes them.  Requires theta >= 0.1.4.
    """
    result = subprocess.run(
        [str(binary), "schema", "--constants"],
        capture_output=True,
        text=True,
        check=True,
    )
    data: dict[str, Any] = json.loads(result.stdout)

    lines = [
        AUTOGEN_HEADER,
        "# Path and file-name constants from theta-static.",
        "# Source of truth: ``theta schema --constants``.",
        "from typing import Final",
        "",
        "",
    ]
    for key, value in sorted(data.items()):
        const_name = key.upper()
        lines.append(f"{const_name}: Final[str] = {value!r}")

    (GENERATED / "constants.py").write_text("\n".join(lines) + "\n")


def write_init() -> None:
    (GENERATED / "__init__.py").write_text(
        AUTOGEN_HEADER
        + "from theta_py._generated import constants, manifest, outcomes, verbs\n\n"
        + '__all__ = ["constants", "manifest", "outcomes", "verbs"]\n',
    )


def write_project_module() -> None:
    import importlib.util
    import sys
    import types as _builtin_types
    import typing

    _KEY = "_theta_outcomes_isolated"
    out_path = GENERATED / "outcomes.py"
    spec = importlib.util.spec_from_file_location(_KEY, out_path)
    assert spec
    assert spec.loader
    out_mod = importlib.util.module_from_spec(spec)

    # HACK
    sys.modules[_KEY] = out_mod
    try:
        spec.loader.exec_module(out_mod)  # type: ignore[union-attr]
    finally:
        sys.modules.pop(_KEY, None)

    GetOutcome = out_mod.GetOutcome
    AgentInfo = out_mod.AgentInfo

    def _type_str(tp: Any) -> str:
        if tp is type(None):
            return "None"
        if isinstance(tp, _builtin_types.UnionType):
            parts = [_type_str(a) for a in tp.__args__]
            non_none = [p for p in parts if p != "None"]
            return f"{non_none[0]} | None" if len(non_none) == 1 and len(parts) == 2 else " | ".join(parts)
        origin = getattr(tp, "__origin__", None)
        args: tuple[Any, ...] = getattr(tp, "__args__", ())
        if origin is typing.Union:
            parts = [_type_str(a) for a in args]
            non_none = [p for p in parts if p != "None"]
            return f"{non_none[0]} | None" if len(non_none) == 1 and len(parts) == 2 else " | ".join(parts)
        if origin is dict:
            return f"dict[{_type_str(args[0])}, {_type_str(args[1])}]"
        if origin is list:
            return f"list[{_type_str(args[0])}]"
        name = getattr(tp, "__name__", None) or getattr(tp, "_name", None) or repr(tp)
        return name

    agent_fields = list(AgentInfo.model_fields.items())
    outcome_fields = [(f, i) for f, i in GetOutcome.model_fields.items() if f != "agent"]

    builtins = {"str", "int", "float", "bool", "list", "dict", "Any", "None", "Path"}
    needed: set[str] = set()
    for _, info in outcome_fields:
        for token in (
            _type_str(info.annotation)
            .replace("[", " ")
            .replace("]", " ")
            .replace("|", " ")
            .replace(",", " ")
            .split()
        ):
            if token and token[0].isupper() and token not in builtins:
                needed.add(token)

    lines: list[str] = [
        AUTOGEN_HEADER,
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "",
    ]
    if needed:
        lines.append("from theta_py._generated.outcomes import (")
        for name in sorted(needed):
            lines.append(f"    {name},")
        lines.append(")")
    lines += [
        "",
        "",
        "class ThetaProjectMixin:",
    ]

    for field, info in agent_fields:
        tp_str = _type_str(info.annotation)
        default = " or []" if tp_str.startswith("list") else ""
        lines += [
            "    @property",
            f"    def {field}(self) -> {tp_str}:",
            f"        return self.manifest.agent.{field}{default}",
            "",
        ]

    for field, info in outcome_fields:
        tp_str = _type_str(info.annotation)
        lines += [
            "    @property",
            f"    def {field}(self) -> {tp_str}:",
            f"        return self._materialized.{field}",
            "",
        ]

    (GENERATED / "project.py").write_text("\n".join(lines) + "\n")


def write_public_init() -> None:
    content = (
        AUTOGEN_HEADER
        + '"""Python bindings for the theta CLI.\n'
        + "\n"
        + "Quick start::\n"
        + "\n"
        + "    from theta_py import ThetaProject, theta\n"
        + "\n"
        + '    with ThetaProject.temp(name="my-agent") as proj:\n'
        + '        proj.add.system(content="You are an expert.")\n'
        + "        proj.sync()\n"
        + "        print(proj.system_prompt)\n"
        + '"""\n'
        + "\n"
        + "from typing import Any\n"
        + "\n"
        + "from theta_py._version import THETA_VERSION\n"
        + "from theta_py.errors import (\n"
        + "    ThetaBinaryNotFoundError,\n"
        + "    ThetaCommandError,\n"
        + "    ThetaError,\n"
        + "    ThetaInvocationError,\n"
        + ")\n"
        + "\n"
        + "__version__ = THETA_VERSION\n"
        + "\n"
        + "\n"
        + "def __getattr__(name: str) -> Any:\n"
        + '    if name == "ThetaProject":\n'
        + "        from theta_py.project import ThetaProject as _tp\n"
        + "        return _tp\n"
        + '    if name == "ThetaManifest":\n'
        + "        from theta_py._generated.manifest import ThetaManifest as _m\n"
        + "        return _m\n"
        + '    _outcomes = {"AgentInfo", "GetOutcome", "MaterializedRule", "MaterializedSkill", "MaterializedTool"}\n'
        + "    if name in _outcomes:\n"
        + "        from theta_py._generated import outcomes as _o\n"
        + "        return getattr(_o, name)\n"
        + "    from theta_py._generated import verbs as _v\n"
        + '    if name == "theta":\n'
        + "        return _v._get_theta()\n"
        + "    if hasattr(_v, name):\n"
        + "        return getattr(_v, name)\n"
        + '    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")\n'
        + "\n"
        + "\n"
        + "__all__ = [\n"
        + '    "THETA_VERSION",\n'
        + '    "AgentInfo",\n'
        + '    "GetOutcome",\n'
        + '    "MaterializedRule",\n'
        + '    "MaterializedSkill",\n'
        + '    "MaterializedTool",\n'
        + '    "Theta",\n'
        + '    "ThetaBinaryNotFoundError",\n'
        + '    "ThetaCommandError",\n'
        + '    "ThetaError",\n'
        + '    "ThetaInvocationError",\n'
        + '    "ThetaManifest",\n'
        + '    "ThetaProject",\n'
        + "]\n"
    )
    (PACKAGE_DIR / "__init__.py").write_text(content)


def write_version(version: str) -> None:
    """Pin THETA_VERSION so the wheel records the binary it was built against."""
    target = PACKAGE_DIR / "_version.py"
    target.write_text(
        AUTOGEN_HEADER + "from typing import Final\n\n" + f'THETA_VERSION: Final[str] = "{version}"\n',
    )


# smoke-test recipes. Keyed by tuple(verb_path). Frozen so codegen cannot be
# silently mutated by an importer.
SMOKE_RECIPES: Mapping[tuple[str, ...], Mapping[str, Any]] = MappingProxyType(
    {
        ("init",): {"setup": "none", "args": {"name": "smoke"}},
        ("check",): {"setup": "init", "args": {}},
        ("describe",): {"setup": "init", "args": {}},
        ("lock",): {"setup": "init", "args": {}},
        ("sync",): {"setup": "init", "args": {}},
        ("get",): {"setup": "init+sync", "args": {}},
        ("tree",): {"setup": "init", "args": {}},
        ("schema",): {
            "setup": "none",
            "args": {},
            "skip": "schema verb dumps full TOML schema, not envelope-shaped",
        },
        ("add", "rule"): {"setup": "init", "args": {"name": "smoke-rule"}},
        ("add", "system"): {"setup": "init", "args": {}},
        ("add", "tool"): {"setup": "init", "args": {"name": "smoke-tool", "command": "echo hi"}},
        ("add", "skill"): {"setup": "init", "args": {"name_or_ref": "smoke-skill"}},
        ("add", "subagent"): {
            "setup": "init",
            "args": {"name": "smoke-subagent", "description": "smoke", "description_only": True},
        },
        ("rm", "rule"): {"setup": "init+rule", "args": {"name": "smoke-rule", "no_sync": True}},
        ("rm", "system"): {
            "setup": "init",
            "args": {"name": "missing", "no_sync": True},
            "skip": "rm of missing entity returns error envelope; not a smoke target",
        },
        ("rm", "tool"): {
            "setup": "init",
            "args": {"name": "missing", "no_sync": True},
            "skip": "rm of missing entity returns error envelope; not a smoke target",
        },
        ("rm", "skill"): {
            "setup": "init",
            "args": {"name": "missing", "no_sync": True},
            "skip": "rm of missing entity returns error envelope; not a smoke target",
        },
        ("rm", "subagent"): {
            "setup": "init",
            "args": {"name": "missing", "no_sync": True},
            "skip": "rm of missing entity returns error envelope; not a smoke target",
        },
        ("rm", "store"): {
            "setup": "init",
            "args": {"name": "missing"},
            "skip": "requires populated system store",
        },
        ("list", "rules"): {"setup": "init", "args": {}},
        ("list", "tools"): {"setup": "init", "args": {}},
        ("list", "skills"): {"setup": "init", "args": {}},
        ("list", "subagents"): {"setup": "init", "args": {}},
        ("list", "store"): {"setup": "init", "args": {}},
        ("cast", "to"): {"setup": "init", "args": {"target": "claude-code"}},
        ("cast", "from"): {
            "setup": "none",
            "args": {"source": "claude-code"},
            "skip": "requires a populated source directory; covered by Rust cast_round_trip tests",
        },
        ("register", "skill"): {
            "setup": "init",
            "args": {"name": "missing"},
            "skip": "requires a populated system store",
        },
        ("register", "rule"): {
            "setup": "init",
            "args": {"name": "missing"},
            "skip": "requires a populated system store",
        },
        ("register", "agent"): {
            "setup": "init",
            "args": {"name": "missing"},
            "skip": "requires a populated system store",
        },
    }
)


def _outcome_for(leaf: dict[str, Any]) -> str:
    return (leaf.get("output_schema") or {}).get("title") or outcome_class_name(leaf["path"])


_SMOKE_HEADER = """\
from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from theta_py import Theta
from theta_py._generated import outcomes, verbs


def _binary_available() -> bool:
    from theta_py.runner import ThetaBinaryNotFoundError, _resolve_binary

    try:
        _resolve_binary(auto_install=False)
        return True
    except (ThetaBinaryNotFoundError, FileNotFoundError):
        return shutil.which("theta") is not None


pytestmark = pytest.mark.skipif(
    not _binary_available(),
    reason="theta binary not resolvable",
)


@pytest.fixture
def workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("THETA_DATA_DIR", str(data_dir))
    monkeypatch.delenv("THETA_CONFIG_DIR", raising=False)
    verbs._theta = None
    yield tmp_path
    verbs._theta = None


def _setup_init(t: Theta) -> None:
    t.init(name="smoke-setup")


def _setup_init_rule(t: Theta) -> None:
    t.init(name="smoke-setup")
    t.add.rule("smoke-rule")


def _setup_init_sync(t: Theta) -> None:
    t.init(name="smoke-setup")
    t.add.system(content="smoke system prompt")
    t.sync()


SETUP: dict[str, callable] = {
    "none": lambda t: None,
    "init": _setup_init,
    "init+rule": _setup_init_rule,
    "init+sync": _setup_init_sync,
}
"""


def _ns_call_expr(path: tuple[str, ...]) -> str:
    method = kwarg_name(path[-1].replace("-", "_"))
    if len(path) == 1:
        return f"t.{method}"
    return f"t.{path[0]}.{method}"


def write_smoke_tests(leaves: list[dict[str, Any]]) -> None:
    target = GENERATED_TESTS / "test_verbs_smoke.py"
    parts: list[str] = [AUTOGEN_HEADER, _SMOKE_HEADER, ""]
    c = parts.append

    for leaf in leaves:
        path = tuple(leaf["path"])
        recipe = SMOKE_RECIPES.get(path)
        if recipe is None:
            continue
        outcome = _outcome_for(leaf)
        fn_safe = "_".join(p.replace("-", "_") for p in path)
        kwargs_repr = ", ".join(f"{k}={v!r}" for k, v in recipe["args"].items())
        ns_callable = _ns_call_expr(path)
        flat_fn = function_name(list(path))
        skip_reason = recipe.get("skip")
        setup_key = recipe["setup"]

        decorator = f"@pytest.mark.skip(reason={skip_reason!r})\n" if skip_reason else ""

        # namespaced surface
        c(
            f"{decorator}"
            f"def test_smoke_{fn_safe}_namespaced(workspace: Path) -> None:\n"
            f"    t = Theta()\n"
            f"    SETUP[{setup_key!r}](t)\n"
            f"    out = {ns_callable}({kwargs_repr})\n"
            f"    assert isinstance(out, outcomes.{outcome})\n"
        )
        c("")

        # flat surface
        c(
            f"{decorator}"
            f"def test_smoke_{fn_safe}_flat(workspace: Path) -> None:\n"
            f"    SETUP[{setup_key!r}](Theta())\n"
            f"    out = verbs.{flat_fn}({kwargs_repr})\n"
            f"    assert isinstance(out, outcomes.{outcome})\n"
        )
        c("")

    # drift detector
    leaf_paths = sorted(tuple(leaf["path"]) for leaf in leaves)
    c("KNOWN_LEAVES: tuple[tuple[str, ...], ...] = (")
    for p in leaf_paths:
        c(f"    {p!r},")
    c(")")
    c("")
    c("RECIPED_LEAVES: frozenset[tuple[str, ...]] = frozenset({")
    for p in sorted(SMOKE_RECIPES.keys()):
        c(f"    {p!r},")
    c("})")
    c("")
    c("")
    c("def test_every_verb_has_a_smoke_recipe() -> None:")
    c("    missing = [p for p in KNOWN_LEAVES if p not in RECIPED_LEAVES]")
    c("    assert not missing, (")
    c("        f'new verbs without a SMOKE_RECIPES entry: {missing}. '")
    c("        f'Add them in src/theta_py/_codegen.py.'")
    c("    )")
    c("")

    target.write_text("\n".join(parts))


def _binary_version(binary: Path) -> str:
    result = subprocess.run(
        [str(binary), "--version"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip().split()[-1]


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate theta_py._generated.")
    parser.add_argument(
        "--binary",
        default=None,
        help="Path to the theta binary. Defaults to theta_py.runner._resolve_binary.",
    )
    parser.add_argument(
        "--theta-version",
        default=None,
        help=(
            "Version string to pin into THETA_VERSION. Defaults to the output "
            "of `theta --version` on the resolved binary. CI passes this "
            "explicitly when building wheels for a tagged theta release."
        ),
    )
    args = parser.parse_args()

    binary = resolve_binary(args.binary)
    version = args.theta_version or _binary_version(binary)
    print(f"codegen: theta binary at {binary} (version {version})")

    for directory in (GENERATED, GENERATED_TESTS):
        directory.mkdir(parents=True, exist_ok=True)
        for child in directory.iterdir():
            if child.name == ".gitignore":
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()

    tree = fetch_verb_tree(binary)
    leaves = iter_leaves(tree)
    write_outcomes_module(leaves)
    write_verbs_module(leaves)
    write_smoke_tests(leaves)
    write_manifest_module(binary)
    write_constants_module(binary)
    write_project_module()
    write_init()
    write_public_init()
    write_version(version)
    print(f"generated {len(leaves)} verb wrappers in {GENERATED}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
