# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.

# Path and file-name constants from theta-static.
# Source of truth: ``theta schema --constants``.
from typing import Final


DOT_THETA_DIR: Final[str] = '.theta'
LOCKFILE: Final[str] = 'theta.lock'
MANIFEST_FILE_NAME: Final[str] = 'theta.toml'
RULES_DIR: Final[str] = 'rules'
SKILL_FILE_NAME: Final[str] = 'SKILL.md'
SKILLS_DIR: Final[str] = 'skills'
SUBAGENTS_DIR_NAME: Final[str] = 'subagents'
SYSTEM_FILE_NAME: Final[str] = 'system.md'
THETA_OUT_DIR_ENV: Final[str] = 'THETA_OUT_DIR'
