# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.
# generated by datamodel-codegen:
#   filename:  manifest.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Agent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    authors: list[str] | None = None
    description: str
    model: str | None = None
    name: str
    tags: list[str] | None = None
    version: str | None = None


class ApplyMode(StrEnum):
    always = 'always'
    model_decision = 'model-decision'
    glob = 'glob'
    manual = 'manual'


class Instructions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rules: dict[str, Any] | None = None
    system: str | None = None


class LocalOrGitRef1(BaseModel):
    branch: str | None = Field(None, description='Explicit branch name')
    file: str
    git: str
    rev: str | None = Field(None, description='Explicit commit SHA')
    tag: str | None = Field(None, description='Explicit tag name')


class LocalOrGitRef2(BaseModel):
    system: str


class Rule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apply: ApplyMode | None = 'always'
    apply_to: list[str] | None = None
    description: str | None = None
    src: str | LocalOrGitRef1 | LocalOrGitRef2
    summary: str | None = None


class SourceRef1(BaseModel):
    branch: str | None = Field(None, description='Explicit branch name')
    git: str
    rev: str | None = Field(None, description='Explicit commit SHA')
    subdirectory: str | None = None
    tag: str | None = Field(None, description='Explicit tag name')


class SourceRef2(BaseModel):
    path: str


class SourceRef3(BaseModel):
    system: str


class Subagent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    model: str | None = None
    name: str
    prompt_path: str | None = None
    ref: str | None = None
    skills: list[str] | None = None
    tools: list[str] | None = None


class Theta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: str = Field(..., alias='schema')


class Tool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: list[str] | None = None
    command: list[str] | None = None
    enabled: bool | None = None
    env: dict[str, Any] | None = None
    headers: dict[str, Any] | None = None
    url: str | None = None


class ThetaManifest(BaseModel):
    """
    The full `theta.toml` manifest.

    Construct via deserialization (`toml::from_str`) followed by `Validate::validate`, or via `minimal_manifest()` for test fixtures. Direct struct-literal construction bypasses validation — callers are responsible for ensuring invariants.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    agent: Agent
    extras: dict[str, Any] | None = None
    harness: dict[str, Any] | None = None
    instructions: Instructions | None = None
    skills: dict[str, Any] | None = None
    subagents: list[Subagent] | None = None
    theta: Theta
    tools: dict[str, Any] | None = None


class Skill(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal: str | None = None
    source: SourceRef1 | SourceRef2 | SourceRef3
    tags: list[str] | None = None
