# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.
# generated by datamodel-codegen:
#   filename:  outcomes.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, conint


class ThetaOutcomes(BaseModel):
    pass


class InitSource(StrEnum):
    scaffold = 'scaffold'
    store = 'store'


class InitOutcome(BaseModel):
    agent_name: str | None = None
    gitignore_appended: bool
    manifest_path: str
    source: InitSource


class CheckOutcome(BaseModel):
    errors: conint(ge=0)
    hints: conint(ge=0)
    valid: bool
    warnings: conint(ge=0)


class DescribeMode(StrEnum):
    read = 'read'
    write = 'write'


class DescribeRule(BaseModel):
    apply: str
    name: str
    source: str
    summary: str | None = None


class DescribeOutcome(BaseModel):
    description: str | None = None
    mode: DescribeMode
    rules: list[DescribeRule] | None = None


class EntityKind(StrEnum):
    """
    Manifest or store entity that the mutation targets.
    """
    rule = 'rule'
    system = 'system'
    tool = 'tool'
    skill = 'skill'
    subagent = 'subagent'
    agent = 'agent'


class MutationKind(StrEnum):
    """
    Verb that performed a mutation against either the manifest or the system store.
    """
    add = 'add'
    remove = 'remove'
    register = 'register'
    unregister = 'unregister'


class MutationSourceKind(StrEnum):
    local = 'local'
    git = 'git'
    store = 'store'
    inline = 'inline'
    description = 'description'


class ListKind(StrEnum):
    rules = 'rules'
    tools = 'tools'
    skills = 'skills'
    subagents = 'subagents'
    store = 'store'


class ListOutcome(BaseModel):
    entries: Any
    kind: ListKind


class LockOutcome(BaseModel):
    lockfile_path: str
    wrote: bool


class SyncOutcome(BaseModel):
    created: conint(ge=0)
    theta_dir: str
    updated: conint(ge=0)


class CastToOutcome(BaseModel):
    files_written: list[str]
    output_dir: str
    target: str


class CastFromOutcome(BaseModel):
    files_written: list[str]
    manifest_path: str
    source: str
    sources_read: list[str]


class TreeNode(BaseModel):
    children: list[TreeNode]
    mode: str | None = None
    name: str


class TreeOutcome(BaseModel):
    tree: TreeNode


class MutationSource(BaseModel):
    """
    Origin description for a newly-added entry. `kind` describes which constructor of the manifest's `src`/`source` union was used; `detail` carries the human-meaningful identifier (path, URL, store name).
    """
    detail: str
    kind: MutationSourceKind


class MutationOutput(BaseModel):
    """
    Uniform payload for every `add` / `rm` / `register` / unregister variant.

    `files_written` and `files_deleted` are project-relative when the operation targets a project, absolute when targeting the system store.
    """
    entity: EntityKind
    files_deleted: list[str]
    files_written: list[str]
    kind: MutationKind
    name: str | None = None
    source: MutationSource | None = None


TreeNode.model_rebuild()
