# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.

from __future__ import annotations

from pathlib import Path

from theta_py._generated.outcomes import (
    MaterializedRule,
    MaterializedSkill,
    MaterializedTool,
)


class ThetaProjectMixin:
    @property
    def authors(self) -> list[str] | None:
        return self.manifest.agent.authors or []

    @property
    def description(self) -> str:
        return self.manifest.agent.description

    @property
    def model(self) -> str | None:
        return self.manifest.agent.model

    @property
    def name(self) -> str:
        return self.manifest.agent.name

    @property
    def tags(self) -> list[str] | None:
        return self.manifest.agent.tags or []

    @property
    def version(self) -> str | None:
        return self.manifest.agent.version

    @property
    def lock_hash(self) -> str | None:
        return self._materialized.lock_hash

    @property
    def rules(self) -> dict[str, MaterializedRule]:
        return self._materialized.rules

    @property
    def skills(self) -> dict[str, MaterializedSkill]:
        return self._materialized.skills

    @property
    def system_prompt(self) -> str | None:
        return self._materialized.system_prompt

    @property
    def tools(self) -> dict[str, MaterializedTool]:
        return self._materialized.tools

