# !!! AUTOGENERATED — DO NOT EDIT BY HAND !!!
# Source of truth: `theta schema --list-verbs`.
# Regenerate with `python -m theta_py._codegen`.

from __future__ import annotations

import os
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from theta_py import runner
from theta_py._generated import outcomes


class Add:
    """`theta add` namespace; methods correspond to subcommands."""

    def __init__(self, theta: Theta) -> None:
        self._theta = theta

    def rule(
        self,
        name: str,
        *,
        system: str | None = None,
        path: str | None = None,
        git: str | None = None,
        branch: str | None = None,
        tag: str | None = None,
        rev: str | None = None,
        file: str | None = None,
        sync: bool = False,
        content: str | None = None,
        summary: str | None = None,
        apply: str | None = None,
        apply_to: str | None = None,
        description: str | None = None,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Scaffold and register a new rule"""
        argv: list[str] = ['add', 'rule']
        argv.append(name)
        if system is not None:
            argv.extend(['--system', system])
        if path is not None:
            argv.extend(['--path', path])
        if git is not None:
            argv.extend(['--git', git])
        if branch is not None:
            argv.extend(['--branch', branch])
        if tag is not None:
            argv.extend(['--tag', tag])
        if rev is not None:
            argv.extend(['--rev', rev])
        if file is not None:
            argv.extend(['--file', file])
        if sync:
            argv.append('--sync')
        if content is not None:
            argv.extend(['--content', content])
        if summary is not None:
            argv.extend(['--summary', summary])
        if apply is not None:
            argv.extend(['--apply', apply])
        if apply_to is not None:
            argv.extend(['--apply-to', apply_to])
        if description is not None:
            argv.extend(['--description', description])
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def system(
        self,
        *,
        path: str | None = None,
        content: str | None = None,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Scaffold and register the system prompt"""
        argv: list[str] = ['add', 'system']
        if path is not None:
            argv.extend(['--path', path])
        if content is not None:
            argv.extend(['--content', content])
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def tool(
        self,
        name: str,
        *,
        command: str | None = None,
        url: str | None = None,
        envs: str | None = None,
        headers: str | None = None,
        extra_args: str | None = None,
        disabled: bool = False,
        registry: str | None = None,
        no_cache: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Register an MCP tool (stdio or HTTP)"""
        argv: list[str] = ['add', 'tool']
        argv.append(name)
        if command is not None:
            argv.extend(['--command', command])
        if url is not None:
            argv.extend(['--url', url])
        if envs is not None:
            argv.extend(['--env', envs])
        if headers is not None:
            argv.extend(['--header', headers])
        if extra_args is not None:
            argv.extend(['--args', extra_args])
        if disabled:
            argv.append('--disabled')
        if registry is not None:
            argv.extend(['--registry', registry])
        if no_cache:
            argv.append('--no-cache')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def skill(
        self,
        name_or_ref: str,
        *,
        name: str | None = None,
        path: str | None = None,
        git: str | None = None,
        branch: str | None = None,
        tag: str | None = None,
        rev: str | None = None,
        subdirectory: str | None = None,
        description: str | None = None,
        tags: str | None = None,
        goal: str | None = None,
        system: bool = False,
        no_sync: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Scaffold or register a skill"""
        argv: list[str] = ['add', 'skill']
        argv.append(name_or_ref)
        if name is not None:
            argv.extend(['--name', name])
        if path is not None:
            argv.extend(['--path', path])
        if git is not None:
            argv.extend(['--git', git])
        if branch is not None:
            argv.extend(['--branch', branch])
        if tag is not None:
            argv.extend(['--tag', tag])
        if rev is not None:
            argv.extend(['--rev', rev])
        if subdirectory is not None:
            argv.extend(['--subdirectory', subdirectory])
        if description is not None:
            argv.extend(['--description', description])
        if tags is not None:
            argv.extend(['--tags', tags])
        if goal is not None:
            argv.extend(['--goal', goal])
        if system:
            argv.append('--system')
        if no_sync:
            argv.append('--no-sync')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def subagent(
        self,
        name: str,
        *,
        agent_ref: str | None = None,
        description: str | None = None,
        model: str | None = None,
        prompt_path: str | None = None,
        tools: str | None = None,
        skills: str | None = None,
        description_only: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Register a subagent (inline or ref)"""
        argv: list[str] = ['add', 'subagent']
        argv.append(name)
        if agent_ref is not None:
            argv.extend(['--agent-ref', agent_ref])
        if description is not None:
            argv.extend(['--description', description])
        if model is not None:
            argv.extend(['--model', model])
        if prompt_path is not None:
            argv.extend(['--prompt-path', prompt_path])
        if tools is not None:
            argv.extend(['--tools', tools])
        if skills is not None:
            argv.extend(['--skills', skills])
        if description_only:
            argv.append('--description-only')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])


class Cast:
    """`theta cast` namespace; methods correspond to subcommands."""

    def __init__(self, theta: Theta) -> None:
        self._theta = theta

    def to(
        self,
        target: str,
        *,
        output: str | None = None,
        force: bool = False,
        notes: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.CastToOutcome:
        """Cast theta.toml to a harness-native config"""
        argv: list[str] = ['cast', 'to']
        argv.append(target)
        if output is not None:
            argv.extend(['--output', output])
        if force:
            argv.append('--force')
        if notes:
            argv.append('--notes')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.CastToOutcome.model_validate(envelope['data'])

    def from_(
        self,
        source: str,
        *,
        input: str | None = None,
        force: bool = False,
        subagent_prompts: str | None = None,
        force_overwrite: bool = False,
        notes: bool = False,
        cross_read: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.CastFromOutcome:
        """Import a harness-native config into theta.toml"""
        argv: list[str] = ['cast', 'from']
        argv.append(source)
        if input is not None:
            argv.extend(['--input', input])
        if force:
            argv.append('--force')
        if subagent_prompts is not None:
            argv.extend(['--subagent-prompts', subagent_prompts])
        if force_overwrite:
            argv.append('--force-overwrite')
        if notes:
            argv.append('--notes')
        if cross_read:
            argv.append('--cross-read')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.CastFromOutcome.model_validate(envelope['data'])


class List:
    """`theta list` namespace; methods correspond to subcommands."""

    def __init__(self, theta: Theta) -> None:
        self._theta = theta

    def rules(
        self,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.ListOutcome:
        """List registered rules"""
        argv: list[str] = ['list', 'rules']
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.ListOutcome.model_validate(envelope['data'])

    def tools(
        self,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.ListOutcome:
        """List registered tools (MCP servers)"""
        argv: list[str] = ['list', 'tools']
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.ListOutcome.model_validate(envelope['data'])

    def skills(
        self,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.ListOutcome:
        """List registered skills"""
        argv: list[str] = ['list', 'skills']
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.ListOutcome.model_validate(envelope['data'])

    def subagents(
        self,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.ListOutcome:
        """List registered subagents"""
        argv: list[str] = ['list', 'subagents']
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.ListOutcome.model_validate(envelope['data'])

    def store(
        self,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.ListOutcome:
        """List contents of the system store"""
        argv: list[str] = ['list', 'store']
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.ListOutcome.model_validate(envelope['data'])


class Register:
    """`theta register` namespace; methods correspond to subcommands."""

    def __init__(self, theta: Theta) -> None:
        self._theta = theta

    def skill(
        self,
        name_or_ref: str,
        *,
        name: str | None = None,
        path: str | None = None,
        git: str | None = None,
        branch: str | None = None,
        tag: str | None = None,
        rev: str | None = None,
        subdirectory: str | None = None,
        description: str | None = None,
        force: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Register a skill into the system store"""
        argv: list[str] = ['register', 'skill']
        argv.append(name_or_ref)
        if name is not None:
            argv.extend(['--name', name])
        if path is not None:
            argv.extend(['--path', path])
        if git is not None:
            argv.extend(['--git', git])
        if branch is not None:
            argv.extend(['--branch', branch])
        if tag is not None:
            argv.extend(['--tag', tag])
        if rev is not None:
            argv.extend(['--rev', rev])
        if subdirectory is not None:
            argv.extend(['--subdirectory', subdirectory])
        if description is not None:
            argv.extend(['--description', description])
        if force:
            argv.append('--force')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def rule(
        self,
        name: str,
        *,
        force: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Register a rule into the system store"""
        argv: list[str] = ['register', 'rule']
        argv.append(name)
        if force:
            argv.append('--force')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def agent(
        self,
        *,
        name: str | None = None,
        force: bool = False,
        no_lock: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Register this agent into the system store"""
        argv: list[str] = ['register', 'agent']
        if name is not None:
            argv.extend(['--name', name])
        if force:
            argv.append('--force')
        if no_lock:
            argv.append('--no-lock')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])


class Rm:
    """`theta rm` namespace; methods correspond to subcommands."""

    def __init__(self, theta: Theta) -> None:
        self._theta = theta

    def rule(
        self,
        name: str,
        *,
        delete: bool = False,
        no_sync: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Remove a rule from the manifest"""
        argv: list[str] = ['rm', 'rule']
        argv.append(name)
        if delete:
            argv.append('--delete')
        if no_sync:
            argv.append('--no-sync')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def system(
        self,
        *,
        delete: bool = False,
        no_sync: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Remove the system prompt from the manifest"""
        argv: list[str] = ['rm', 'system']
        if delete:
            argv.append('--delete')
        if no_sync:
            argv.append('--no-sync')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def tool(
        self,
        name: str,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Remove a tool from the manifest"""
        argv: list[str] = ['rm', 'tool']
        argv.append(name)
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def skill(
        self,
        name: str,
        *,
        delete: bool = False,
        no_sync: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Remove a skill from the manifest"""
        argv: list[str] = ['rm', 'skill']
        argv.append(name)
        if delete:
            argv.append('--delete')
        if no_sync:
            argv.append('--no-sync')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def subagent(
        self,
        name: str,
        *,
        delete: bool = False,
        no_sync: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Remove a subagent from the manifest"""
        argv: list[str] = ['rm', 'subagent']
        argv.append(name)
        if delete:
            argv.append('--delete')
        if no_sync:
            argv.append('--no-sync')
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])

    def store(
        self,
        kind: str,
        name: str,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.MutationOutput:
        """Unregister a resource from the system store"""
        argv: list[str] = ['rm', 'store']
        argv.append(kind)
        argv.append(name)
        envelope = self._theta._run(argv, cwd=cwd, env=env)
        return outcomes.MutationOutput.model_validate(envelope['data'])


class Theta:
    def __init__(
        self,
        *,
        binary: str | os.PathLike[str] | None = None,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> None:
        self._binary: Path = Path(binary) if binary is not None else runner._resolve_binary()
        self._cwd = cwd
        self._env = env
        self.add = Add(self)
        self.cast = Cast(self)
        self.list = List(self)
        self.register = Register(self)
        self.rm = Rm(self)

    def _run(
        self,
        argv: list[str],
        *,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> dict[str, Any]:
        # Resolution order: explicit per-call cwd --> instance cwd --> live os.getcwd()
        # at call time. The last branch matches subprocess semantics: a long-lived
        # Theta() that was constructed before chdir() still follows the process.
        if cwd is not None:
            effective_cwd = cwd
        elif self._cwd is not None:
            effective_cwd = self._cwd
        else:
            effective_cwd = os.getcwd()
        effective_env = env if env is not None else self._env
        return runner.run_with_binary(self._binary, argv, cwd=effective_cwd, env=effective_env)

    def init(
        self,
        *,
        from_: str | None = None,
        name: str | None = None,
        force: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.InitOutcome:
        """Scaffold a new theta.toml in the current directory"""
        argv: list[str] = ['init']
        if from_ is not None:
            argv.extend(['--from', from_])
        if name is not None:
            argv.extend(['--name', name])
        if force:
            argv.append('--force')
        envelope = self._run(argv, cwd=cwd, env=env)
        return outcomes.InitOutcome.model_validate(envelope['data'])

    def check(
        self,
        *,
        schema_only: bool = False,
        skip_materialization: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.CheckOutcome:
        """Validate theta.toml and materialized dependencies"""
        argv: list[str] = ['check']
        if schema_only:
            argv.append('--schema-only')
        if skip_materialization:
            argv.append('--skip-materialization')
        envelope = self._run(argv, cwd=cwd, env=env)
        return outcomes.CheckOutcome.model_validate(envelope['data'])

    def describe(
        self,
        description: str | None = None,
        *,
        set: str | None = None,
        rules: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.DescribeOutcome:
        """Read or set the agent description"""
        argv: list[str] = ['describe']
        if description is not None:
            argv.append(description)
        if set is not None:
            argv.extend(['--set', set])
        if rules:
            argv.append('--rules')
        envelope = self._run(argv, cwd=cwd, env=env)
        return outcomes.DescribeOutcome.model_validate(envelope['data'])

    def lock(
        self,
        *,
        force: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.LockOutcome:
        """Resolve all sources and write theta.lock"""
        argv: list[str] = ['lock']
        if force:
            argv.append('--force')
        envelope = self._run(argv, cwd=cwd, env=env)
        return outcomes.LockOutcome.model_validate(envelope['data'])

    def sync(
        self,
        *,
        force: bool = False,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.SyncOutcome:
        """Materialize dependencies into .theta/"""
        argv: list[str] = ['sync']
        if force:
            argv.append('--force')
        envelope = self._run(argv, cwd=cwd, env=env)
        return outcomes.SyncOutcome.model_validate(envelope['data'])

    def tree(
        self,
        cwd: str | os.PathLike[str] | None = None,
        env: Mapping[str, str] | None = None,
    ) -> outcomes.TreeOutcome:
        """Print the subagent dependency tree"""
        argv: list[str] = ['tree']
        envelope = self._run(argv, cwd=cwd, env=env)
        return outcomes.TreeOutcome.model_validate(envelope['data'])


_theta: Theta | None = None


def _get_theta() -> Theta:
    global _theta
    if _theta is None:
        _theta = Theta()
    return _theta


def init(
    *,
    from_: str | None = None,
    name: str | None = None,
    force: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.InitOutcome:
    """Scaffold a new theta.toml in the current directory"""
    return _get_theta().init(from_=from_, name=name, force=force, cwd=cwd, env=env)


def check(
    *,
    schema_only: bool = False,
    skip_materialization: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.CheckOutcome:
    """Validate theta.toml and materialized dependencies"""
    return _get_theta().check(schema_only=schema_only, skip_materialization=skip_materialization, cwd=cwd, env=env)


def describe(
    description: str | None = None,
    *,
    set: str | None = None,
    rules: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.DescribeOutcome:
    """Read or set the agent description"""
    return _get_theta().describe(description, set=set, rules=rules, cwd=cwd, env=env)


def lock(
    *,
    force: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.LockOutcome:
    """Resolve all sources and write theta.lock"""
    return _get_theta().lock(force=force, cwd=cwd, env=env)


def sync(
    *,
    force: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.SyncOutcome:
    """Materialize dependencies into .theta/"""
    return _get_theta().sync(force=force, cwd=cwd, env=env)


def tree(
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.TreeOutcome:
    """Print the subagent dependency tree"""
    return _get_theta().tree(cwd=cwd, env=env)


def add_rule(
    name: str,
    *,
    system: str | None = None,
    path: str | None = None,
    git: str | None = None,
    branch: str | None = None,
    tag: str | None = None,
    rev: str | None = None,
    file: str | None = None,
    sync: bool = False,
    content: str | None = None,
    summary: str | None = None,
    apply: str | None = None,
    apply_to: str | None = None,
    description: str | None = None,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Scaffold and register a new rule"""
    return _get_theta().add.rule(name, system=system, path=path, git=git, branch=branch, tag=tag, rev=rev, file=file, sync=sync, content=content, summary=summary, apply=apply, apply_to=apply_to, description=description, cwd=cwd, env=env)


def add_system(
    *,
    path: str | None = None,
    content: str | None = None,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Scaffold and register the system prompt"""
    return _get_theta().add.system(path=path, content=content, cwd=cwd, env=env)


def add_tool(
    name: str,
    *,
    command: str | None = None,
    url: str | None = None,
    envs: str | None = None,
    headers: str | None = None,
    extra_args: str | None = None,
    disabled: bool = False,
    registry: str | None = None,
    no_cache: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Register an MCP tool (stdio or HTTP)"""
    return _get_theta().add.tool(name, command=command, url=url, envs=envs, headers=headers, extra_args=extra_args, disabled=disabled, registry=registry, no_cache=no_cache, cwd=cwd, env=env)


def add_skill(
    name_or_ref: str,
    *,
    name: str | None = None,
    path: str | None = None,
    git: str | None = None,
    branch: str | None = None,
    tag: str | None = None,
    rev: str | None = None,
    subdirectory: str | None = None,
    description: str | None = None,
    tags: str | None = None,
    goal: str | None = None,
    system: bool = False,
    no_sync: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Scaffold or register a skill"""
    return _get_theta().add.skill(name_or_ref, name=name, path=path, git=git, branch=branch, tag=tag, rev=rev, subdirectory=subdirectory, description=description, tags=tags, goal=goal, system=system, no_sync=no_sync, cwd=cwd, env=env)


def add_subagent(
    name: str,
    *,
    agent_ref: str | None = None,
    description: str | None = None,
    model: str | None = None,
    prompt_path: str | None = None,
    tools: str | None = None,
    skills: str | None = None,
    description_only: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Register a subagent (inline or ref)"""
    return _get_theta().add.subagent(name, agent_ref=agent_ref, description=description, model=model, prompt_path=prompt_path, tools=tools, skills=skills, description_only=description_only, cwd=cwd, env=env)


def cast_to(
    target: str,
    *,
    output: str | None = None,
    force: bool = False,
    notes: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.CastToOutcome:
    """Cast theta.toml to a harness-native config"""
    return _get_theta().cast.to(target, output=output, force=force, notes=notes, cwd=cwd, env=env)


def cast_from(
    source: str,
    *,
    input: str | None = None,
    force: bool = False,
    subagent_prompts: str | None = None,
    force_overwrite: bool = False,
    notes: bool = False,
    cross_read: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.CastFromOutcome:
    """Import a harness-native config into theta.toml"""
    return _get_theta().cast.from_(source, input=input, force=force, subagent_prompts=subagent_prompts, force_overwrite=force_overwrite, notes=notes, cross_read=cross_read, cwd=cwd, env=env)


def list_rules(
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.ListOutcome:
    """List registered rules"""
    return _get_theta().list.rules(cwd=cwd, env=env)


def list_tools(
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.ListOutcome:
    """List registered tools (MCP servers)"""
    return _get_theta().list.tools(cwd=cwd, env=env)


def list_skills(
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.ListOutcome:
    """List registered skills"""
    return _get_theta().list.skills(cwd=cwd, env=env)


def list_subagents(
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.ListOutcome:
    """List registered subagents"""
    return _get_theta().list.subagents(cwd=cwd, env=env)


def list_store(
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.ListOutcome:
    """List contents of the system store"""
    return _get_theta().list.store(cwd=cwd, env=env)


def register_skill(
    name_or_ref: str,
    *,
    name: str | None = None,
    path: str | None = None,
    git: str | None = None,
    branch: str | None = None,
    tag: str | None = None,
    rev: str | None = None,
    subdirectory: str | None = None,
    description: str | None = None,
    force: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Register a skill into the system store"""
    return _get_theta().register.skill(name_or_ref, name=name, path=path, git=git, branch=branch, tag=tag, rev=rev, subdirectory=subdirectory, description=description, force=force, cwd=cwd, env=env)


def register_rule(
    name: str,
    *,
    force: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Register a rule into the system store"""
    return _get_theta().register.rule(name, force=force, cwd=cwd, env=env)


def register_agent(
    *,
    name: str | None = None,
    force: bool = False,
    no_lock: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Register this agent into the system store"""
    return _get_theta().register.agent(name=name, force=force, no_lock=no_lock, cwd=cwd, env=env)


def rm_rule(
    name: str,
    *,
    delete: bool = False,
    no_sync: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Remove a rule from the manifest"""
    return _get_theta().rm.rule(name, delete=delete, no_sync=no_sync, cwd=cwd, env=env)


def rm_system(
    *,
    delete: bool = False,
    no_sync: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Remove the system prompt from the manifest"""
    return _get_theta().rm.system(delete=delete, no_sync=no_sync, cwd=cwd, env=env)


def rm_tool(
    name: str,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Remove a tool from the manifest"""
    return _get_theta().rm.tool(name, cwd=cwd, env=env)


def rm_skill(
    name: str,
    *,
    delete: bool = False,
    no_sync: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Remove a skill from the manifest"""
    return _get_theta().rm.skill(name, delete=delete, no_sync=no_sync, cwd=cwd, env=env)


def rm_subagent(
    name: str,
    *,
    delete: bool = False,
    no_sync: bool = False,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Remove a subagent from the manifest"""
    return _get_theta().rm.subagent(name, delete=delete, no_sync=no_sync, cwd=cwd, env=env)


def rm_store(
    kind: str,
    name: str,
    cwd: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
) -> outcomes.MutationOutput:
    """Unregister a resource from the system store"""
    return _get_theta().rm.store(kind, name, cwd=cwd, env=env)

